version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin234
      POSTGRES_DB: asset_management
    ports:
      - "5016:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend-service
    depends_on:
      - postgres
    ports:
      - "3023:3023"
    environment:
      DATABASE_URL: postgres://postgres:admin234@postgres:5432/asset_management

  employee_asset:
    build:
      context: ./Employee-Asset
      dockerfile: Dockerfile
    container_name: employee-asset-service
    ports:
      - "8031:80"
    depends_on:
      - backend

  hr_asset:
    build:
      context: ./Hr Asset
      dockerfile: Dockerfile
    container_name: hr-asset-service
    ports:
      - "8032:80"
    depends_on:
      - backend

volumes:
  postgres_data:

